queries = [
    # Biclustering
    "Run spectral biclustering on a checkerboard matrix.",
    "Apply spectral coclustering to synthetic data.",
    "Cluster newsgroups data using biclustering.",
    "Visualize biclusters in a heatmap.",
    "Use normalized cuts in biclustering.",
    "Label clusters in a biclustering plot.",
    "Compare biclustering with coclustering.",
    "Create synthetic checkerboard dataset.",
    "Run spectral biclustering and visualize rows vs columns.",
    "Extract co-clusters from document-word matrix.",
    "Find biclusters in a sparse matrix.",
    "Plot clustered data from spectral coclustering.",
    "Compare two biclustering algorithms.",
    "Visualize biclustered data with a matrix image.",
    "Assign each sample to a bicluster.",
    "Sort matrix rows and columns based on biclusters.",
    "Preprocess dataset for biclustering.",
    "Evaluate clustering performance using ARI.",
    "Group text documents using coclustering.",
    "Compare original matrix with rearranged biclustered version.",

    # Calibration
    "Plot calibration curves for multiple classifiers.",
    "Compare probabilities from calibrated classifiers.",
    "Calibrate classifiers using isotonic regression.",
    "Calibrate a random forest classifier.",
    "Plot reliability diagrams.",
    "Calibrate a model using sigmoid method.",
    "Evaluate Brier score for calibrated classifiers.",
    "Plot predicted probabilities vs true outcomes.",
    "Calibrate probabilities for multiclass classifier.",
    "Use CalibratedClassifierCV with cross-validation.",
    "Compare accuracy before and after calibration.",
    "Train SVM with calibration on digits data.",
    "Use calibration for improving decision thresholds.",
    "Calibrate logistic regression with sigmoid fitting.",
    "Apply calibration methods on sklearn classifiers.",
    "Assess probability quality using calibration curve.",
    "Visualize multiclass calibration heatmaps.",
    "Use calibration to improve ROC performance.",
    "Check model confidence using calibration.",
    "Train and calibrate an SVM on toy data.",

    # Classification
    "Compare multiple classifiers on toy data.",
    "Visualize classification decision boundaries.",
    "Train and test a QDA model.",
    "Fit and visualize LDA classifier.",
    "Use classification probabilities for uncertainty estimation.",
    "Apply different classifiers to digits dataset.",
    "Evaluate classifiers using accuracy and visual plots.",
    "Compare QDA and LDA decision boundaries.",
    "Plot classifier scores with respect to threshold.",
    "Train multiple classifiers and display their predictions.",
    "Use LDA for dimensionality reduction.",
    "Visualize class probability maps.",
    "Compare classifier performance using test accuracy.",
    "Visualize predictions from LDA and QDA.",
    "Create an LDA classifier on synthetic data.",
    "Use digits dataset for classification.",
    "Assess classifier calibration using probabilities.",
    "Plot true vs predicted class probabilities.",
    "Compare predictions across different models.",
    "Visualize support vectors of an SVM classifier.",

    # Covariance Estimation
    "Compare Ledoit-Wolf and OAS estimators.",
    "Estimate Mahalanobis distances.",
    "Plot empirical vs robust covariance matrices.",
    "Fit sparse inverse covariance matrix.",
    "Visualize covariance estimation for multiple estimators.",
    "Calculate Mahalanobis distances for outlier detection.",
    "Use Ledoit-Wolf shrinkage estimator.",
    "Estimate sparse covariance using graphical lasso.",
    "Compare covariance estimation accuracy.",
    "Visualize support of sparse precision matrix.",
    "Apply robust covariance estimation to outliers.",
    "Estimate covariance on multivariate data.",
    "Use OAS for high-dimensional data.",
    "Draw confidence ellipses using Mahalanobis distance.",
    "Compare covariance matrix estimators on same data.",
    "Show difference between robust and empirical covariance.",
    "Estimate inverse covariance with sparsity constraints.",
    "Plot covariance matrices as heatmaps.",
    "Analyze correlation structure of dataset.",
    "Detect anomalies with robust Mahalanobis distance.",

    # Cross Decomposition
    "Compare CCA, PLS and PCR.",
    "Perform PLS regression on simulated data.",
    "Compare PCR and PLS regression results.",
    "Plot cross-decomposition results for two datasets.",
    "Reduce dimension using cross decomposition.",
    "Train a model using partial least squares.",
    "Use canonical correlation analysis on feature pairs.",
    "Visualize projections of CCA vs PLS.",
    "Run CCA on toy dataset.",
    "Evaluate regression performance with PCR.",
    "Perform cross decomposition with 2D features.",
    "Fit CCA to multi-output data.",
    "Compare PLS1 and PLS2 for regression.",
    "Visualize scores from PCR and PLS.",
    "Use cross decomposition for dimensionality reduction.",
    "Use cross-validation to evaluate PCR.",
    "Project data to latent space with PLS.",
    "Analyze relationship between two data matrices.",
    "Interpret weights and scores of PLS.",
    "Apply CCA to high-dimensional dataset.",

    # Dataset Examples
    "Create a random multilabel classification dataset.",
    "Plot label distribution in multilabel dataset.",
    "Visualize multilabel classification targets.",
    "Generate multilabel dataset with sklearn.",
    "Simulate dataset for multilabel classification.",
    "Plot histogram of multilabel frequency.",
    "Use make_multilabel_classification to generate data.",
    "Create synthetic dataset for multilabel task.",
    "View example samples from multilabel dataset.",
    "Inspect sparsity of multilabel data.",
    "Use sparse format for multilabel dataset.",
    "Generate multilabel dataset with noise.",
    "Visualize multilabel data as matrix plot.",
    "Analyze correlation between labels.",
    "Generate features and labels for multilabel learning.",
    "Count how many labels each sample has.",
    "Use multilabel data with classifier.",
    "Build baseline model for multilabel dataset.",
    "Split multilabel dataset into train and test.",
    "Preprocess multilabel dataset using standard scaler.",

    # Decision Trees
    "Visualize decision tree regression.",
    "Train a regression tree on sinusoidal data.",
    "Plot cost complexity pruning path.",
    "Display structure of decision tree.",
    "Train a decision tree classifier on iris data.",
    "Use post-pruning on decision tree.",
    "Compare performance before and after pruning.",
    "Visualize tree nodes and decision splits.",
    "Analyze training and testing errors with pruning.",
    "Display internal structure of a tree model.",
    "Extract feature importances from decision tree.",
    "Color decision tree nodes by impurity.",
    "Train decision tree with max_depth parameter.",
    "Fit a tree regressor and plot results.",
    "Use DecisionTreeClassifier on a toy dataset.",
    "Prune decision tree using alpha.",
    "Print tree structure in text form.",
    "Use cost-complexity to control overfitting.",
    "Plot predicted output of decision tree regressor.",
    "Visualize branching of nodes in tree classifier.",

    # Feature Selection
    "Compare F-test and mutual information.",
    "Use SelectFromModel on diabetes dataset.",
    "Build feature selection pipeline.",
    "Perform recursive feature elimination on digits data.",
    "Run RFE with cross-validation.",
    "Visualize selected features in pipeline.",
    "Select top k features with mutual info.",
    "Compare performance with selected features.",
    "Train model with reduced feature set.",
    "Evaluate classifier after feature elimination.",
    "Select informative features using L1 regularization.",
    "Visualize feature rankings from RFE.",
    "Combine feature selection with PCA.",
    "Perform ANOVA F-test on dataset.",
    "Select features using tree-based models.",
    "Use feature importance for dimensionality reduction.",
    "Compare model accuracy before and after feature selection.",
    "Use pipeline to standardize and select features.",
    "Select optimal number of features with CV.",
    "Plot feature selection performance curves."
]

queries += [
    # Clustering
    "Cluster handwritten digits using KMeans and visualize labels.",
    "Run KMeans++ initialization for digit clustering.",
    "Compare standard KMeans and KMeans++ on RGB data.",
    "Perform bisecting KMeans for cluster refinement.",
    "Segment coin images using Ward hierarchical clustering.",
    "Apply mean-shift clustering on 2D toy data.",
    "Analyze cluster stability across multiple runs.",
    "Compute silhouette scores for KMeans clusters.",
    "Compare clustering assignments with adjusted measures.",
    "Use adjusted Rand index to evaluate clustering.",
    "Run MiniBatchKMeans on large digit dataset.",
    "Compare Birch and MiniBatchKMeans performance.",
    "Compute linkage matrices for hierarchical clustering.",
    "Visualize agglomerative clustering dendrogram.",
    "Define connectivity constraints in AgglomerativeClustering.",
    "Segment interactive coin image using clustering.",
    "Run OPTICS clustering on noisy data.",
    "Apply HDBSCAN for density‑based grouping.",
    "Perform DBSCAN and visualize cluster cores.",
    "Compare different hierarchical linkage strategies.",
    "Use AffinityPropagation for unsupervised clustering.",
    "Test KMeans assumptions on synthetic data.",
    "Cluster low‑dimensional dense data with KMeans stability.",
    "Apply feature agglomeration vs univariate selection.",
    "Cluster digits using agglomeration hierarchy.",
    "Use inductive clustering to assign new samples.",
    "Extract face patches using dictionary clustering.",
    "Compare structured vs unstructured Ward clustering.",
    "Apply silhouette plot for KMeans elbow method.",
    "Run segmentation on a toy image grid.",
    "Compress face images using cluster centers.",
    "Visualize cluster comparison across algorithms.",
    "Run KMeans with varying k on digits.",
    "Plot cluster boundaries for different algorithms.",
    "Show cluster assignments overlaying original images.",
    "Compute and plot membership probabilities.",
    "Visualize connectivity graph for hierarchical clustering.",
    "Segment coin using spectral or hierarchical clustering.",
    "Compare clustering metrics: ARI, NMI, homogeneity.",
    "Visualize clusters in 2D PCA projection.",
    "Run Birch clustering vs KMeans on face data.",
    "Cluster toy image by pixel intensity.",
    "Compare cluster shapes using different methods.",
    "Plot cluster compactness across parameter ranges.",
    "Evaluate cluster purity on labeled datasets.",
    "Run cluster assignment on test set samples.",
    "Apply bisecting KMeans incrementally.",
    "Explore cluster over‑segmentation effects.",
    "Aggregate features with agglomerative clustering.",
    "Cluster images at multiple resolutions.",
    "Visualize how new data fits existing clusters.",
    "Use spectro‑graphic clustering for audio features.",

    # Decomposition
    "Perform ICA blind source separation on mixed audio.",
    "Compare PCA and LDA on face images.",
    "Decompose face dataset using PCA components.",
    "Apply varimax rotation in factor analysis.",
    "Compare ICA vs PCA for components extraction.",
    "Run image denoising using PCA reconstructions.",
    "Perform IncrementalPCA on streaming data.",
    "Apply kernel PCA with RBF kernel.",
    "Use PCA and FA to select components.",
    "Plot PCA on iris dataset.",
    "Perform sparse coding on image patches.",
    "Compare matrix reconstruction errors between methods.",
    "Visualize PCA basis vectors for faces.",
    "Use ICA to unmix audio signal sources.",
    "Apply kernel PCA to non‑linear structure.",
    "Run IncrementalPCA in batches.",
    "Visualize latent factors from varimax analysis.",
    "Compare KL divergence across decomposition methods.",
    "Cluster based on sparse coding representations.",
    "Filter image noise via low‑rank reconstruction.",
    "Compute explained variance ratio from PCA.",
    "Visualize reconstructed vs original images.",

    # Developing Estimators
    "Check if estimator object is fitted in sklearn.",
    "Implement is_fitted check in custom estimator.",

    # Ensemble Methods
    "Train gradient boosting on categorical features.",
    "Apply early stopping in gradient boosting.",
    "Compare random forest and histogram gradient boosting.",
    "Plot feature importances from random forest.",
    "Run multioutput regression with random forest.",
    "Perform AdaBoost regression on toy data.",
    "Apply histogram‑based gradient boosting regressor.",
    "Train gradient boosting with OOB score.",
    "Apply regularized gradient boosting regression.",
    "Compare forest embedding vs gradient boosting.",
    "Fit isolation forest for anomaly detection.",
    "Use monotonic constraints in gradient boosting.",
    "Train AdaBoost classifier for multiclass data.",
    "Plot voting regressor combining multiple models.",
    "Visualize decision regions in voting classifier.",
    "Compare bias‑variance tradeoff for ensembles.",
    "Plot OOB error curves for ensembles.",
    "Run stack predictors meta‑model.",
    "Plot forest vs boosting histogram results.",
    "Evaluate early stopping influence on error.",
    "Compare feature transformation via ensemble.",
    "Analyze forest embedding of iris dataset.",
    "Use AdaBoost two‑class classifier on synthetic data.",
    "Visualize region boundaries of voting regressor.",
    "Train HGBT regressor for smooth predictions.",
    "Plot gradient boosting quantile regression.",
    "Perform feature importance ranking in ensemble.",
    "Cluster embeddings produced by random forest.",
    "Analyze isolation forest outlier scores.",
    "Compare gradient boosting categorical method.",
    "Plot stacked model predictions vs ground truth.",
    "Compare ensemble OOB metrics vs CV.",
    "Plot monotonic constraint effects on boosting.",
    "Run AdaBoost regression with quantile loss.",
    "Visualize variance reduction via boosting steps.",
    "Plot feature transformation pipeline with ensemble.",
    "Evaluate ensemble prediction latency across methods.",
    "Combine estimators in voting regressor ensemble.",
    "Plot forest vs HGBT regression curves.",
    "Assess ensemble calibration across models.",
    "Visualize AdaBoost multiclass decision boundaries.",
    "Compare random forest and gradient boosting speeds.",
    "Inspect feature importances for boosting vs forest.",
    "Use histogram gradient boosting for categorical data.",
    "Plot bias‑variance decomposition for ensembles.",
    "Train AdaBoost with early stopping on My data.",
    "Visualize decision regions in stacked regressor.",
    "Plot OOB for forest and boosted model.",
    "Evaluate robustness of isolation forest on noise.",
    "Plot ensemble model complexity influence.",

    # Real-World Examples
    "Do a bike sharing demand regression",
    "Run face recognition using eigenfaces.",
    "Denoise handwritten digits with autoencoder methods.",
    "Create lagged features for time series forecasting.",
    "Analyze model complexity effect on generalization.",
    "Run out‑of‑core classification on large dataset.",
    "Detect wine outliers using isolation forest.",
    "Measure prediction latency for different models.",
    "Model species distribution using presence data.",
    "Engineer cyclical features for datetime variables.",
    "Extract topics using NMF and LDA.",
    "Plot stock market returns over time.",
    "Compute Wikipedia principal eigenvector for PageRank.",
    "Compare NMF vs LDA topic coherence.",
    "Apply L1‑based tomography to reconstruct image.",
    "Train face recognition pipeline with PCA.",
    "Use denoising to enhance digit readability.",
    "Build lagged features for multivariate time series.",
    "Plot training vs test error across complexity.",
    "Stream data by out‑of‑core classifier.",
    "Detect anomalies in wine dataset automatically.",
    "Time prediction latency under concurrency.",
    "Use species distribution model for ecology data.",
    "Encode weekday cycles with sin/cos transforms.",
    "Compare topics from NMF and LDA models.",
    "Plot stock price prediction intervals.",
    "Use PageRank eigenvector centrality on network.",

    # Frozen Estimators
    "Use frozen estimators for consistency tests.",
    "Compare behavior of unfrozen vs frozen models.",

    # Gaussian Mixture Models
    "Plot GMM density PDF for mixture components.",
    "Analyze GMM covariance type effects.",
    "Run GMM on sinusoidal synthetic data.",
    "Visualize concentration prior influence in GMM.",
    "Compare different GMM initializations.",
    "Select optimal number of GMM components.",
    "Plot cluster assignments from GMM.",
    "Run Bayesian GMM with Dirichlet prior.",
    "Visualize elliptical mixture clusters.",
    "Compute model likelihood across GMMs.",
    "Compare full vs tied covariance in GMM.",
    "Use GMM to model multimodal distribution.",
    "Plot covariance matrices from GMM components.",
    "Analyze mixture selection criteria like BIC.",

    # Gaussian Processes
    "Fit noisy GPR on 1D function data.",
    "Compare GPR and kernel ridge regression.",
    "Model CO2 concentration using GPR.",
    "Run GPR with noisy target observations.",
    "Classify iris data using GPC.",
    "Apply GPR to structured spatial data.",
    "Use GPC to model XOR pattern.",
    "Plot prior and posterior of GPR.",
    "Visualize isoprobability contours with GPC.",
    "Train GPC classifier on binary data.",
    "Evaluate GPR prediction uncertainty intervals.",
    "Compare different GPR kernels on regression.",
    "Model periodic signals using Gaussian processes.",
    "Use GPR on environmental structured data.",
    "Plot posterior samples from GPR model.",
    "Use GPC to estimate class probabilities.",
    "Model noisy time‑series with GPR.",
    "Compare predictive variance from GPR and KRR.",
    "Visualize Gaussian process mean function.",
    "Use GPR to fit heteroskedastic data.",
]

