queries = [
    # Biclustering
    "Run spectral biclustering on a checkerboard matrix.",
    "Apply spectral coclustering to synthetic data.",
    "Cluster newsgroups data using biclustering.",
    "Visualize biclusters in a heatmap.",
    "Use normalized cuts in biclustering.",
    "Label clusters in a biclustering plot.",
    "Compare biclustering with coclustering.",
    "Create synthetic checkerboard dataset.",
    "Run spectral biclustering and visualize rows vs columns.",
    "Extract co-clusters from document-word matrix.",
    "Find biclusters in a sparse matrix.",
    "Plot clustered data from spectral coclustering.",
    "Compare two biclustering algorithms.",
    "Visualize biclustered data with a matrix image.",
    "Assign each sample to a bicluster.",
    "Sort matrix rows and columns based on biclusters.",
    "Preprocess dataset for biclustering.",
    "Evaluate clustering performance using ARI.",
    "Group text documents using coclustering.",
    "Compare original matrix with rearranged biclustered version.",

    # Calibration
    "Plot calibration curves for multiple classifiers.",
    "Compare probabilities from calibrated classifiers.",
    "Calibrate classifiers using isotonic regression.",
    "Calibrate a random forest classifier.",
    "Plot reliability diagrams.",
    "Calibrate a model using sigmoid method.",
    "Evaluate Brier score for calibrated classifiers.",
    "Plot predicted probabilities vs true outcomes.",
    "Calibrate probabilities for multiclass classifier.",
    "Use CalibratedClassifierCV with cross-validation.",
    "Compare accuracy before and after calibration.",
    "Train SVM with calibration on digits data.",
    "Use calibration for improving decision thresholds.",
    "Calibrate logistic regression with sigmoid fitting.",
    "Apply calibration methods on sklearn classifiers.",
    "Assess probability quality using calibration curve.",
    "Visualize multiclass calibration heatmaps.",
    "Use calibration to improve ROC performance.",
    "Check model confidence using calibration.",
    "Train and calibrate an SVM on toy data.",

    # Classification
    "Compare multiple classifiers on toy data.",
    "Visualize classification decision boundaries.",
    "Train and test a QDA model.",
    "Fit and visualize LDA classifier.",
    "Use classification probabilities for uncertainty estimation.",
    "Apply different classifiers to digits dataset.",
    "Evaluate classifiers using accuracy and visual plots.",
    "Compare QDA and LDA decision boundaries.",
    "Plot classifier scores with respect to threshold.",
    "Train multiple classifiers and display their predictions.",
    "Use LDA for dimensionality reduction.",
    "Visualize class probability maps.",
    "Compare classifier performance using test accuracy.",
    "Visualize predictions from LDA and QDA.",
    "Create an LDA classifier on synthetic data.",
    "Use digits dataset for classification.",
    "Assess classifier calibration using probabilities.",
    "Plot true vs predicted class probabilities.",
    "Compare predictions across different models.",
    "Visualize support vectors of an SVM classifier.",

    # Covariance Estimation
    "Compare Ledoit-Wolf and OAS estimators.",
    "Estimate Mahalanobis distances.",
    "Plot empirical vs robust covariance matrices.",
    "Fit sparse inverse covariance matrix.",
    "Visualize covariance estimation for multiple estimators.",
    "Calculate Mahalanobis distances for outlier detection.",
    "Use Ledoit-Wolf shrinkage estimator.",
    "Estimate sparse covariance using graphical lasso.",
    "Compare covariance estimation accuracy.",
    "Visualize support of sparse precision matrix.",
    "Apply robust covariance estimation to outliers.",
    "Estimate covariance on multivariate data.",
    "Use OAS for high-dimensional data.",
    "Draw confidence ellipses using Mahalanobis distance.",
    "Compare covariance matrix estimators on same data.",
    "Show difference between robust and empirical covariance.",
    "Estimate inverse covariance with sparsity constraints.",
    "Plot covariance matrices as heatmaps.",
    "Analyze correlation structure of dataset.",
    "Detect anomalies with robust Mahalanobis distance.",

    # Cross Decomposition
    "Compare CCA, PLS and PCR.",
    "Perform PLS regression on simulated data.",
    "Compare PCR and PLS regression results.",
    "Plot cross-decomposition results for two datasets.",
    "Reduce dimension using cross decomposition.",
    "Train a model using partial least squares.",
    "Use canonical correlation analysis on feature pairs.",
    "Visualize projections of CCA vs PLS.",
    "Run CCA on toy dataset.",
    "Evaluate regression performance with PCR.",
    "Perform cross decomposition with 2D features.",
    "Fit CCA to multi-output data.",
    "Compare PLS1 and PLS2 for regression.",
    "Visualize scores from PCR and PLS.",
    "Use cross decomposition for dimensionality reduction.",
    "Use cross-validation to evaluate PCR.",
    "Project data to latent space with PLS.",
    "Analyze relationship between two data matrices.",
    "Interpret weights and scores of PLS.",
    "Apply CCA to high-dimensional dataset.",

    # Dataset Examples
    "Create a random multilabel classification dataset.",
    "Plot label distribution in multilabel dataset.",
    "Visualize multilabel classification targets.",
    "Generate multilabel dataset with sklearn.",
    "Simulate dataset for multilabel classification.",
    "Plot histogram of multilabel frequency.",
    "Use make_multilabel_classification to generate data.",
    "Create synthetic dataset for multilabel task.",
    "View example samples from multilabel dataset.",
    "Inspect sparsity of multilabel data.",
    "Use sparse format for multilabel dataset.",
    "Generate multilabel dataset with noise.",
    "Visualize multilabel data as matrix plot.",
    "Analyze correlation between labels.",
    "Generate features and labels for multilabel learning.",
    "Count how many labels each sample has.",
    "Use multilabel data with classifier.",
    "Build baseline model for multilabel dataset.",
    "Split multilabel dataset into train and test.",
    "Preprocess multilabel dataset using standard scaler.",

    # Decision Trees
    "Visualize decision tree regression.",
    "Train a regression tree on sinusoidal data.",
    "Plot cost complexity pruning path.",
    "Display structure of decision tree.",
    "Train a decision tree classifier on iris data.",
    "Use post-pruning on decision tree.",
    "Compare performance before and after pruning.",
    "Visualize tree nodes and decision splits.",
    "Analyze training and testing errors with pruning.",
    "Display internal structure of a tree model.",
    "Extract feature importances from decision tree.",
    "Color decision tree nodes by impurity.",
    "Train decision tree with max_depth parameter.",
    "Fit a tree regressor and plot results.",
    "Use DecisionTreeClassifier on a toy dataset.",
    "Prune decision tree using alpha.",
    "Print tree structure in text form.",
    "Use cost-complexity to control overfitting.",
    "Plot predicted output of decision tree regressor.",
    "Visualize branching of nodes in tree classifier.",

    # Feature Selection
    "Compare F-test and mutual information.",
    "Use SelectFromModel on diabetes dataset.",
    "Build feature selection pipeline.",
    "Perform recursive feature elimination on digits data.",
    "Run RFE with cross-validation.",
    "Visualize selected features in pipeline.",
    "Select top k features with mutual info.",
    "Compare performance with selected features.",
    "Train model with reduced feature set.",
    "Evaluate classifier after feature elimination.",
    "Select informative features using L1 regularization.",
    "Visualize feature rankings from RFE.",
    "Combine feature selection with PCA.",
    "Perform ANOVA F-test on dataset.",
    "Select features using tree-based models.",
    "Use feature importance for dimensionality reduction.",
    "Compare model accuracy before and after feature selection.",
    "Use pipeline to standardize and select features.",
    "Select optimal number of features with CV.",
    "Plot feature selection performance curves."
]
